<?php
// Do not edit this file
$language = array(
	'blog_comments' => "Enable comments",
	'blog_privacy_comments' => "Enable comments privacy",
	'blog_privacy_public' => "Enable public privacy",
	'blog_privacy_view' => "Enable blog privacy",
	'blog_rating' => "Blog rating",
	'blog_views' => "Count blog views",
	'blogs_active' => "Enable blogs",
	'blogs_gallery' => "Enable public page",
	'blogs_preview_chars' => "Blog preview length",
	'public_blogs_per_page' => "Public blogs per page",
	'user_blogs_per_page' => "User blogs per page"
);