<?php
// Do not edit this file
$language = array(
	'albums_browse' => "Browse albums",
	'albums_limit' => "Max albums",
	'albums_post' => "Create albums",
	'albums_search' => "Search albums",
	'albums_view' => "View albums",
	'pictures_access' => "Access pictures",
	'pictures_approve' => "Auto approve pictures",
	'pictures_limit' => "Max pictures",
	'pictures_manage' => "Manage pictures",
	'pictures_post' => "Upload pictures",
	'pictures_view' => "View pictures"
);