<?php
// Do not edit this file
$language = array(
	'email' => "Your email",
	'message' => "Message",
	'message_sent' => "Message has been successfully sent, thank you!",
	'name' => "Your name",
	'subject' => "Subject"
);