<?php
// Do not edit this file
$language = array(
	'album_privacy_public' => "Enable public privacy",
	'album_privacy_view' => "Enable privacy",
	'album_rating' => "Album rating",
	'album_views' => "Count views",
	'albums_gallery' => "Enable public page",
	'group_albums' => "Albums",
	'picture_comments' => "Enable comments",
	'picture_dimensions' => "Picture dimensions",
	'picture_dimensions_max' => "Max picture dimensions",
	'picture_dimensions_t' => "Thumbnail dimensions",
	'picture_max_size' => "Max picture file size",
	'picture_privacy_comments' => "Enable comments privacy",
	'picture_rating' => "Picture rating",
	'picture_upload_limit' => "File upload limit",
	'picture_views' => "Count views",
	'pictures_active' => "Enable pictures",
	'public_albums_per_page' => "Public albums per page",
	'user_albums_per_page' => "User albums per page",
	'user_pictures_per_page' => "Pictures per page"
);