<?php
// Do not edit this file
$language = array(
	'no_template' => "Newsletter template was not found.",
	'no_templates' => "There are no newsletter templates at this time.",
	'template_delete?' => "Are you sure you want to delete this template?",
	'template_deleted' => "Newsletter template has been successfully deleted.",
	'template_edit' => "Edit template",
	'template_new' => "New template",
	'template_saved' => "Newsletter template has been successfully saved."
);