<?php
// Do not edit this file
$language = array(
	'blog' => "Blog",
	'blog_delete' => "Delete blog",
	'blog_delete?' => "Are you sure you want to delete this blog?",
	'blog_deleted' => "Blog has been successfully deleted.",
	'blog_edit' => "Edit blog",
	'blog_limit_reached' => "You have reached your post limit of %limit% blogs. You may delete some of the existing blog entries to be able to add new ones.",
	'blog_new' => "Add blog",
	'blog_saved' => "Blog has been successfully saved.",
	'blog_view' => "View entry",
	'no_blog' => "Blog entry does not seem to exist.",
	'no_blogs' => "There are no blogs at this time.",
	'no_blogs_self' => "You didn't add any blog entries yet."
);