<?php
// Do not edit this file
$language = array(
	'action_delete' => "Delete",
	'action_delete?' => "Are you sure you want to delete this item from your timeline?",
	'actions_load' => "View more",
	'actions_load_last' => "There is no more activity to show.",
	'actions_none' => "It's quiet around here... be the first one to write something!",
	'message' => "Message",
	'message_delete?' => "Are you sure you want to delete this message?",
	'message_deleted' => "Message has been successfully deleted.",
	'message_edit' => "Edit message",
	'message_placeholder' => "Type your message here...",
	'message_post' => "[poster.name] wrote on [name]'s wall:",
	'message_post_self' => "[poster.name] wrote:",
	'message_saved' => "Message has been successfully saved.",
	'no_message' => "Message does not seem to exist.",
	'no_messages' => "There are no messages at this time.",
	'timeline_message' => "Timeline",
	'timeline_public' => "All activities",
	'timeline_user' => "My news",
	'classified_ad_post' => "[name] posted a new classified listing:",
	'picture_post' => "[name] added [params.count] pictures to the album [album]:",
	'user_picture' => "[name] uploaded a new profile picture:",
	'user_signup' => "[name] has just signed up. Say hello!",
	'blog_post' => "[name] wrote a new blog entry:"
);