<?php
// Do not edit this file
$language = array(
	'ad_comments' => "Enable comments",
	'ad_currency' => "Display currency",
	'ad_expiration' => "Listing expiration",
	'ad_preview_chars' => "Listing preview length",
	'ad_privacy_comments' => "Enable comments privacy",
	'ad_rating' => "Listing rating",
	'ad_views' => "Count ad views",
	'ads_gallery' => "Enable public page",
	'classifieds_active' => "Enable classifieds",
	'group_pictures' => "Pictures",
	'max_gallery_ads' => "Default number of listings",
	'picture_dimensions' => "Picture dimensions",
	'picture_dimensions_max' => "Max picture dimensions",
	'picture_dimensions_t' => "Thumbnail dimensions",
	'picture_max_size' => "Max picture file size",
	'picture_upload_limit' => "File upload limit",
	'pictures_per_page' => "Pictures per page",
	'public_ads_per_page' => "Public listing per page",
	'user_ads_per_page' => "User listing per page"
);