<?php
// Do not edit this file
$language = array(
	'invoice_error' => "Could not create the invoice.",
	'invoices' => "Purchase history",
	'no_invoice' => "Invoice does not seem to exist.",
	'no_invoices_user' => "You did not make any purchases yet.",
	'payment' => "Payment",
	'payment_button' => "Pay with %s",
	'payment_invalid' => "Invalid payment gateway form.",
	'payment_method_select' => "Select payment method",
	'payment_redirecting' => "Redirecting to payment processor...",
	'receipt_id' => "Receipt ID",
	'transaction_view' => "View transaction"
);