<?php
// Do not edit this file
$language = array(
	'notices_none' => "You don't have any notifications yet.",
	'timeline_comment' => "%user commented on your %timeline%.",
	'timeline_like' => "%user liked your timeline %post%.",
	'timeline_message_comment' => "%user commented on your timeline %message%.",
	'timeline_message_like' => "%user liked your timeline %message%.",
	'timeline_message_post' => "%user posted on your %timeline%.",
	'timeline_message_vote' => "%user rated your timeline %message%.",
	'timeline_vote' => "%user rated your timeline %post%.",
	'classified_ad_comment' => "%user commented on your %classified ad%.",
	'classified_ad_like' => "%user liked your %classified ad%.",
	'classified_ad_vote' => "%user rated your %classified ad%.",
	'picture_ablum_like' => "%user liked your %album%.",
	'picture_ablum_vote' => "%user rated your %album%.",
	'picture_comment' => "%user commented on your %picture%.",
	'picture_like' => "%user liked your %picture%.",
	'picture_vote' => "%user rated your %picture%.",
	'blog_comment' => "%user commented on your %blog%.",
	'blog_like' => "%user liked your %blog%.",
	'blog_vote' => "%user rated your %blog%."
);