<?php
// Do not edit this file
$language = array(
	'no_plans' => "There are no membership plans yet.",
	'plan_cycle' => "Billing cycle",
	'plan_delete?' => "Are you sure you want to delete this membership plan?",
	'plan_deleted' => "Membership plan has been successfully deleted.",
	'plan_edit' => "Edit plan",
	'plan_group' => "Assign to group",
	'plan_new' => "New plan",
	'plan_saved' => "Membership plan has been successfully saved.",
	'plan_show_signup' => "Show on signup",
	'plan_signup' => "Signup"
);