<?php
// Do not edit this file
$language = array(
	'credits_manage' => "Manage credits",
	'credits_purchase' => "Purchase credits",
	'gateways_manage' => "Manage gateways",
	'plans_manage' => "Manage plans",
	'plans_purchase' => "Purchase subscription",
	'transactions_manage' => "Manage transactions"
);