<?php
// Do not edit this file
$language = array(
	'gateway_in_use' => "You may not uninstall a payment gateway that has already been used for payments. You may deactivate it instead or remove related transactions and then uninstall it.",
	'gateway_installed' => "Payment gateway has been successfully installed. You may now edit its settings to enable it.",
	'gateway_uninstall?' => "Are you sure you want to uninstall this payment gateway?",
	'gateway_uninstalled' => "Payment gateway has been successfully uninstalled."
);