<?php
// Do not edit this file
$language = array(
	'actions_per_page' => "Activities per page",
	'comments_per_page' => "Comments per page",
	'group_messages' => "Messaging",
	'group_notices' => "Notifications",
	'message_max_length' => "Maximum message length",
	'message_min_length' => "Minimum message length",
	'notices_cleanup_delay' => "Clean up delay (days)",
	'notices_per_page' => "Notifications per page",
	'privacy_edit' => "Enable timeline privacy",
	'timeline_active' => "Enable timeline",
	'timeline_comments' => "Enable comments",
	'timeline_profile' => "Show timeline in profile",
	'timeline_public_feed' => "Enable public feed",
	'timeline_rating' => "Timeline rating",
	'timeline_user_feed' => "Enable user feed"
);