<?php
// Do not edit this file
$language = array(
	'footer' => "Footer",
	'header' => "Header",
	'no_template' => "Email template does not seem to exist.",
	'no_templates' => "Could not fetch email templates from the database.",
	'template_message_html' => "HTML message",
	'template_message_text' => "Plain text message",
	'template_saved' => "Email template has been successfully updated.",
	'template_select' => "Select template",
	'template_subject' => "Subject",
	'users_account_confirm' => "Email address verification",
	'users_account_declined' => "New user declined",
	'users_account_welcome' => "New user confirmed",
	'users_friend_confirmed' => "Friend request confirmed",
	'users_friend_request' => "Friend request",
	'users_password_lost' => "Lost password request",
	'users_password_new' => "New password assigned",
	'messages_new' => "New private message"
);