<?php
// Do not edit this file
$language = array(
	'license_change' => "Change license key",
	'license_change_skip' => "Click %here% if you do not want to change your license key now.",
	'license_domain' => "Valid domain",
	'license_folder' => "Valid directory",
	'license_invalid' => "License key does not seem to be valid.",
	'license_ip' => "Valid IP address",
	'license_key' => "License key",
	'license_login' => "Type in your administrator login details and new license key below. Or click %here% if you do not want to change your license key now.",
	'license_new' => "New license key",
	'license_owner' => "Registered owner",
	'no_license' => "License information could not be found. Make sure the software is installed correctly or fill in your license key below."
);