<?php
// Do not edit this file
$language = array(
	'no_gateway' => "Payment gateway was not found.",
	'no_gateways' => "No payment gateways were found.",
	'no_gateways_user' => "Administrator did not set up any payment gateways yet."
);