<?php
// Do not edit this file
$language = array(
	'entry_delete?' => "Are you sure you want to delete this entry?",
	'entry_deleted' => "News entry has been successfully deleted.",
	'entry_edit' => "Edit entry",
	'entry_new' => "Add entry",
	'entry_saved' => "News entry has been successfully saved.",
	'no_entry' => "News entry does not seem to exist."
);