<?php
// Do not edit this file
$language = array(
	'item_invalid' => "Invalid item ID.",
	'report_exists' => "You have already reported this item.",
	'report_message' => "Comments",
	'report_saved' => "Your report has been successfully submitted.",
	'report_subject' => "Subject",
	'report_submit' => "Submit report",
	'subject_invalid' => "Invalid subject ID."
);