<?php
// Do not edit this file
$language = array(
	'no_packages' => "There are no credit packages yet.",
	'package_delete?' => "Are you sure you want to delete this package?",
	'package_deleted' => "Package has been successfully deleted.",
	'package_edit' => "Edit package",
	'package_new' => "New package",
	'package_saved' => "Package has been successfully saved."
);