<?php
// Do not edit this file
$language = array(
	'no_template' => "Template does not seem to exist.",
	'no_template_settings' => "This template does not have any settings.",
	'no_templates' => "No templates were found.",
	'template_default' => "You may not uninstall default system template. Set a different default system template first before uninstalling this one.",
	'template_installed' => "Template has been successfully installed.",
	'template_uninstall?' => "Are you sure you want to uninstall this template?",
	'template_uninstalled' => "Template has been successfully uninstalled."
);