<?php
// Do not edit this file
$language = array(
	'no_templates' => "There are no message templates at this time.",
	'template_delete?' => "Are you sure you want to delete this template?",
	'template_deleted' => "Message template has been successfully deleted.",
	'template_edit' => "Edit template",
	'template_message' => "Message",
	'template_new' => "New template",
	'template_saved' => "Message template has been successfully saved.",
	'template_subject' => "Subject"
);