<?php
// Do not edit this file
$language = array(
	'blogs_access' => "Access blogs",
	'blogs_approve' => "Auto approve blogs",
	'blogs_browse' => "Browse blogs",
	'blogs_limit' => "Max blogs",
	'blogs_manage' => "Manage blogs",
	'blogs_post' => "Post blogs",
	'blogs_search' => "Search blogs",
	'blogs_view' => "View blogs"
);