<?php
// Do not edit this file
$language = array(
	'comment' => "Comment",
	'comment_body' => "Comment",
	'comment_delete' => "Delete",
	'comment_delete?' => "Are you sure you want to delete this comment?",
	'comment_deleted' => "Comment has been successfully deleted.",
	'comment_edit' => "Edit comment",
	'comment_new' => "Post comment",
	'comment_saved' => "Comment has been successfully saved.",
	'comments_delay_reached' => "In order to prevent spam, you may not post more than %comments comments per %time %type. Please wait before posting another comment.",
	'comments_enable' => "Enable comments",
	'likes_enable' => "Enable likes",
	'no_comment' => "Comment does not seem to exist.",
	'no_comments' => "There are no comments at this time.",
	'rating_enable' => "Enable rating"
);