<?php
// Do not edit this file
$language = array(
	'approve' => "Approve",
	'approve_email' => "Approve + Email",
	'decline' => "Decline",
	'decline_email' => "Decline + Email",
	'install' => "Install",
	'plugin_select' => "Select plugin",
	'settings' => "Settings",
	'settings_saved' => "Settings have been successfully saved.",
	'translate' => "Translate",
	'uninstall' => "Uninstall",
	'website_view' => "View site"
);