<?php
// Do not edit this file
$language = array(
	'no_service' => "Authentication service does not seem to exist.",
	'no_services' => "No authentication services were found.",
	'service_in_use' => "You may not uninstall authentication service that is being used by some of your users. You may deactivate it instead.",
	'service_installed' => "Authentication service has been sucessfully installed.",
	'service_uninstall?' => "Are you sure you want to uninstall this authentication service?",
	'service_uninstalled' => "Authentication service has been sucessfully uninstalled."
);