<?php
// Do not edit this file
$language = array(
	'permissions_ca' => "User permissions",
	'permissions_cp' => "Control panel permissions",
	'permissions_edit' => "Edit permissions",
	'permissions_saved' => "Permissions have been successfully saved.",
	'users_account_cancel' => "Cancel account",
	'users_authentication' => "Manage authentication",
	'users_friends_browse' => "Browse user friends",
	'users_friends_view' => "View friends",
	'users_groups' => "Manage user groups",
	'users_groups_browse' => "Browse user groups",
	'users_groups_view' => "View user groups",
	'users_manage' => "Manage users",
	'users_pictures' => "Manage pictures",
	'users_pictures_approve' => "Approve pictures",
	'users_search_access' => "Access search",
	'users_search_access_advanced' => "Access advanced search",
	'users_types' => "Manage user types",
	'users_types_browse' => "Browse user types",
	'users_types_view' => "View user types",
	'users_visitors_anon' => "Browse profiles anonymously",
	'users_visitors_browse' => "Browse profile visitors",
	'users_visitors_limit' => "Max profile visitors"
);