<?php
// Do not edit this file
$language = array(
	'privacy_timeline' => "Recent activity privacy",
	'privacy_timeline_messages' => "Who can post on my wall",
	'timeline_message_post' => "New timeline messages",
	'timeline_classified_post' => "New classified listings",
	'timeline_picture_post' => "New pictures",
	'options_general' => "General",
	'privacy_friends' => "Who may view my friends",
	'privacy_profile' => "Who may view my profile",
	'privacy_saved' => "Privacy settings have been successfully saved.",
	'timeline_user_picture' => "New profile picture",
	'timeline_blog_post' => "New blog entries"
);