<?php
// Do not edit this file
$language = array(
	'counters_update?' => "Are you sure you want to update counters for this plugin?",
	'no_plugin' => "Selected plugin does not seem to support counter recalculation feature.",
	'progress_done' => "System counters have been successfully updated for %1 plugin.",
	'progress_redirect' => "If nothing happens for a few minutes, click %here% to continue.",
	'progress_status' => "Updating counters: %1 out of %2"
);