<?php
// Do not edit this file
$language = array(
	'cities_manage' => "Manage cities",
	'city_deleted' => "City has been successfully deleted.",
	'city_edit' => "Edit city",
	'city_new' => "New city",
	'city_saved' => "City has been successfully updated.",
	'countries_manage' => "Manage countries",
	'country_deleted' => "Country has been successfully deleted.",
	'country_edit' => "Edit country",
	'country_new' => "New country",
	'country_saved' => "Country has been successfully updated.",
	'item_delete?' => "Are you sure you want to delete this item?",
	'no_cities' => "No cities were found in this state.",
	'no_city' => "City does not seem to exist.",
	'no_countries' => "No countries were found.",
	'no_country' => "Country does not seem to exist.",
	'no_state' => "State does not seem to exist.",
	'no_states' => "No states were found in this country.",
	'state_deleted' => "State has been successfully deleted.",
	'state_edit' => "Edit state",
	'state_new' => "New state",
	'state_saved' => "State has been successfully updated.",
	'states_manage' => "Manage states"
);