<?php
// Do not edit this file
$language = array(
	'actions_delete' => "Delete posts",
	'messages_delay_limit' => "Max messages per time slot",
	'messages_delay_time' => "Time slot",
	'messages_delay_type' => "Time slot type",
	'messages_manage' => "Manage messages",
	'messages_post' => "Post messages"
);