<?php
// Do not edit this file
$language = array(
	'change_languages' => "Change languages",
	'change_templates' => "Change templates",
	'email_templates_manage' => "Manage email templates",
	'fields_manage' => "Manage custom fields",
	'geo_manage' => "Manage geo database",
	'languages_manage' => "Manage languages",
	'license_manage' => "Manage license",
	'meta_tags_manage' => "Manage meta tags",
	'plugins_manage' => "Manage plugins",
	'settings_manage' => "Manage settings",
	'site_access_cp' => "Access control panel",
	'site_access_offline' => "Access site offline",
	'site_login' => "Login to account",
	'storage_manage' => "Manage storages",
	'templates_manage' => "Manage templates",
	'counters_manage' => "Manage counters"
);