<?php
// Do not edit this file
$language = array(
	'no_plan' => "Membership plan does not seem to exist.",
	'no_plans_user' => "Administrator did not create any subscription packages yet.",
	'plans' => "Subscription plans"
);