<?php
// Do not edit this file
$language = array(
	'comments_active' => "Enable comments",
	'comments_per_page' => "Comments per page",
	'group_general' => "General",
	'max_length' => "Maximum length",
	'min_length' => "Minimum length"
);