<?php
// Do not edit this file
$language = array(
	'meta_description' => "Description",
	'meta_keywords' => "Keywords",
	'meta_tags_saved' => "Meta tags have been successfully saved.",
	'meta_title' => "Title",
	'no_meta_tags' => "This plugin doesn't seem to have any meta tags in its configuration.",
	'site_index' => "Homepage"
);