<?php
// Do not edit this file
$language = array(
	'notifications_saved' => "Notification settings have been successfully saved.",
	'notify_friends_accept' => "When my friend request is accepted",
	'notify_friends_request' => "When I receive a friend request",
	'options_general' => "General",
	'notify_messages' => "When I receive a new private message"
);