<?php
// Do not edit this file
$language = array(
	'group_copy' => "Copy permissions",
	'group_delete_self' => "You may not delete the user group you're currently assigned to.",
	'group_delete_system' => "You may not delete this user group because it is used by the system.",
	'group_delete_users' => "You may not delete this user group because it contains members. You must first delete its members.",
	'group_delete?' => "Are you sure you want to delete this user group?",
	'group_deleted' => "User group has been successfully deleted.",
	'group_edit' => "Edit group",
	'group_new' => "New group",
	'group_saved' => "User group has been successfully saved.",
	'groups_select_limit' => "You may not select more than %groups groups at a time.",
	'no_group' => "User group does not seem to exist.",
	'permissions_edit' => "Edit permissions"
);