<?php
// Do not edit this file
$language = array(
	'news_active' => "Enable news",
	'news_blog' => "Use news as site blog",
	'news_comments' => "Enable comments",
	'news_per_page' => "News per page",
	'news_preview_chars' => "News preview length",
	'news_rating' => "News rating",
	'news_views' => "Count news views"
);