<?php
// Do not edit this file
$language = array(
	'no_service' => "Storage service does not seem to exist.",
	'no_services' => "There are no storage services at this time.",
	'service_installed' => "Storage service has been successfully installed.",
	'service_uninstall?' => "Are you sure you want to uninstall this storage service?",
	'service_uninstalled' => "Storage service has been successfully uninstalled.",
	'storage_default' => "This is a default storage. Select a different default storage before uninstalling this one.",
	'storage_in_use' => "You may not uninstall storage service that has files linked to it. You may set a different storage service as default instead if you haven't yet."
);