<?php
// Do not edit this file
$language = array(
	'messages_access' => "Access messages",
	'messages_browse' => "Browse messages",
	'messages_characters_limit' => "Max characters",
	'messages_credits' => "Require credits",
	'messages_delay_limit' => "Max messages per time slot",
	'messages_delay_time' => "Time slot",
	'messages_delay_type' => "Time slot type",
	'messages_limit' => "Max conversations",
	'messages_manage' => "Manage messages",
	'messages_reply' => "Reply to messages from",
	'messages_send' => "Send messages",
	'messages_templates' => "Use message templates",
	'messages_view' => "Read messages",
	'templates_manage' => "Manage message templates"
);