<?php
// Do not edit this file
$language = array(
	'file_delete' => "Remove",
	'file_extensions' => "Allowed extensions: %extensions",
	'file_max_size' => "Max file size: %size",
	'file_select' => "Select file",
	'file_select_multi' => "Select files",
	'file_upload' => "Upload file",
	'file_upload_error' => "File could not be uploaded.",
	'file_upload_multi' => "Upload files",
	'file_uploaded' => "Uploaded",
	'files_clear' => "Clear list",
	'files_limit_reached' => "You may not upload more than %1 file at a time.",
	'files_limit_reached_multi' => "You may not upload more than %1 files at a time.",
	'picture_rotate_left' => "Rotate left",
	'picture_rotate_right' => "Rotate right",
	'picture_thumbnail_edit' => "Edit thumbnail",
	'size_kb' => "kb",
	'size_mb' => "mb"
);