<?php
// Do not edit this file
$language = array(
	'credits_current' => "Virtual credits",
	'credits_purchase' => "Get more credits",
	'expire_date' => "Expiration date",
	'invoices' => "Purchase history",
	'plan_change' => "Upgrade account",
	'plan_current' => "Subscription",
	'language' => "Language",
	'settings_saved' => "Account settings have been successfully saved.",
	'template' => "Template",
	'time_zone' => "Time zone"
);