<?php
// Do not edit this file
$language = array(
	'no_blocked_user' => "This user does not seem to be in your blacklist.",
	'no_blocked_users' => "You don't have anybody in your blacklist yet.",
	'user_blocked' => "User has been successfully blocked.",
	'user_duplicate' => "This user is already in your blacklist.",
	'user_unblocked' => "User has been successfully unblocked."
);