<?php
// Do not edit this file
$language = array(
	'no_class' => "Plugin does not seem to have the Install class.",
	'no_class_method' => "Plugin does not seem to have the %method method.",
	'no_plugin_settings' => "This plugin does not have any settings.",
	'no_plugins' => "No plugins were found.",
	'plugin_author' => "Author",
	'plugin_installed' => "Plugin has been successfully installed.",
	'plugin_new_version' => "New version %version is available",
	'plugin_required' => "To use this plugin you must have the following plugin installed: %plugin",
	'plugin_system' => "This is a system plugin and it may not be uninstalled.",
	'plugin_system_required' => "Your software version must be %version or higher to use this plugin.",
	'plugin_uninstall?' => "Are you sure you want to uninstall this plugin?",
	'plugin_uninstalled' => "Plugin has been successfully uninstalled.",
	'plugin_update' => "Update now",
	'plugin_update_latest' => "You already appear to be running the latest version of this plugin.",
	'plugin_updated' => "Plugin has been successfully updated to the latest version.",
	'plugin_version' => "Version",
	'plugin_view' => "Plugin details"
);