<?php
// Do not edit this file
$language = array(
	'no_type' => "User type does not seem to exist.",
	'profile_questions' => "Profile questions",
	'type_delete_self' => "You may not delete the user type you're currently assigned to.",
	'type_delete_system' => "You may not delete this user type because it is used by the system.",
	'type_delete_users' => "You may not delete this user type because it contains members. You must first delete its members.",
	'type_delete?' => "Are you sure you want to delete this user type?",
	'type_deleted' => "User type has been successfully deleted.",
	'type_duplicate_field_name' => "You may not select duplicate name fields.",
	'type_duplicate_keyword' => "Keyword is already used in another user type.",
	'type_edit' => "Edit type",
	'type_fields_name' => "Name fields",
	'type_name_field_invalid' => "One of the field names is invalid.",
	'type_name_field_missing' => "At least one name field must be selected.",
	'type_new' => "New type",
	'type_saved' => "User type has been successfully saved."
);