<?php
// Do not edit this file
$language = array(
	'newsletter_delete?' => "Are you sure you want to delete this newsletter?",
	'newsletter_deleted' => "Newsletter has been successfully deleted.",
	'newsletter_edit' => "Edit newsletter",
	'newsletter_message_html' => "HTML message",
	'newsletter_message_text' => "Plain text message",
	'newsletter_new' => "New newsletter",
	'newsletter_recipients' => "Recipients",
	'newsletter_recipients_edit' => "Edit recipients",
	'newsletter_reset' => "Reset newsletter",
	'newsletter_reset?' => "Are you sure you want to reset the total number of sent emails for this newsletter?",
	'newsletter_resume' => "Resume newsletter",
	'newsletter_resume?' => "Are you sure you want to resume sending this newsletter?",
	'newsletter_review' => "Review",
	'newsletter_send' => "Send newsletter",
	'newsletter_send?' => "Are you sure you want to send this newsletter?",
	'newsletter_sending' => "Sending newsletter",
	'newsletter_sending_redirect' => "If nothing happens for a few minutes, click %here% to continue.",
	'newsletter_sending_status' => "%1 out of %2",
	'newsletter_sent' => "Newsletter has been succesfully sent.",
	'newsletter_subject' => "Subject",
	'newsletter_test' => "Send test email",
	'newsletter_test?' => "Are you sure you want to send a test email?",
	'newsletters_test_none' => "You didn't specify test email on the %settings% page.",
	'no_newsletter' => "Newsletter was not found.",
	'no_newsletters' => "There are no newsletters at this time."
);