<?php
// Do not edit this file
$language = array(
	'duplicate_keyword' => "Keyword is already used in another language pack.",
	'language_default' => "You may not uninstall default system language. Set a different default system language first before uninstalling this one.",
	'language_delete?' => "Are you sure you want to delete this language pack?",
	'language_deleted' => "Language pack has been successfully deleted.",
	'language_edit' => "Edit language pack",
	'language_english' => "You may not delete English language pack. ",
	'language_export' => "Export",
	'language_export?' => "Are you sure you want to export the contents of this language pack from the database into the language pack files?",
	'language_exported' => "Language pack has been successfully exported to \"%path\" folder.",
	'language_import' => "Import",
	'language_import?' => "Are you sure you want to import the contents of this language pack from the language pack files into the database?",
	'language_imported' => "Language pack has been successfully imported from \"%path\" folder.",
	'language_new' => "New language pack",
	'language_saved' => "Language translations have been successfully saved.",
	'language_section' => "Sections",
	'language_translate' => "Translate",
	'language_translation_not_installed' => "Not installed",
	'language_translation_pct' => "Translation",
	'language_uninstall?' => "Are you sure you want to uninstall this language pack?",
	'language_uninstalled' => "Language has been successfully uninstalled.",
	'no_language' => "Language does not seem to exist.",
	'no_languages' => "Could not fetch languages from the database."
);