<?php
// Do not edit this file
$language = array(
	'ads_access' => "Access classifieds",
	'ads_approve' => "Auto approve listings",
	'ads_browse' => "Browse classifieds",
	'ads_credits' => "Require credits",
	'ads_limit' => "Max listings",
	'ads_manage' => "Manage listings",
	'ads_post' => "Post listings",
	'ads_search' => "Search classifieds",
	'ads_view' => "View listings",
	'pictures_approve' => "Auto approve pictures",
	'pictures_limit' => "Max pictures",
	'pictures_manage' => "Manage pictures",
	'pictures_post' => "Upload pictures"
);