<?php
// Do not edit this file
$language = array(
	'no_transaction' => "Transaction does not seem to exist.",
	'no_transactions' => "There are no transactions at this time.",
	'transaction_delete?' => "Are you sure you want to delete this transaction?",
	'transaction_deleted' => "Transaction has been successfully deleted.",
	'transaction_id' => "Transaction ID"
);