<?php
// Do not edit this file
$language = array(
	'credits_active' => "Enable virtual credits",
	'credits_signup_bonus' => "Bonus credits at registration",
	'currency' => "Currency",
	'group_invoices' => "Invoices",
	'invoices_active' => "Enable purchase history",
	'invoices_per_page' => "Invoices per page",
	'language_credits' => "Credits",
	'language_gateways' => "Gateways",
	'language_plans' => "Subscriptions",
	'language_transactions' => "Transactions",
	'subscriptions_active' => "Enable subscriptions"
);