<?php
// Do not edit this file
$language = array(
	'comments_delete' => "Delete comments",
	'comments_manage' => "Manage comments",
	'comments_post' => "Post comments",
	'comments_view' => "View comments",
	'manage_comments' => "Manage comments",
	'post_comments' => "Post comments",
	'view_comments' => "View coments"
);