<?php
// Do not edit this file
$language = array(
	'no_actions' => "Could not fetch report actions. Make sure reported item's plugin supports it.",
	'no_actions_method' => "Could not fetch selected action method. Make sure reported item's plugin supports it.",
	'no_report' => "Report does not seem to exist.",
	'no_reports' => "Nobody reported anything yet.",
	'no_url' => "Could not fetch item's URL. Make sure reported item's plugin supports it.",
	'report_action_failed' => "Selected action did not return successful result.",
	'report_action_select' => "Select action",
	'report_actions' => "Actions",
	'report_delete' => "Delete report",
	'report_dismiss' => "Dismiss",
	'report_dismiss?' => "Are you sure you want to dismiss this report?",
	'report_dismissed' => "Report has been successfully dismissed.",
	'report_item' => "Item",
	'report_item_deactivate' => "Deactivate item",
	'report_item_delete' => "Delete item",
	'report_view' => "View",
	'reporter' => "Reporter"
);