<?php
// Do not edit this file
$language = array(
	'no_subject' => "Report subject does not seem to exist.",
	'no_subjects' => "There doesn't seem to be any report subjects.",
	'subject_delete?' => "Are you sure you want to delete this report subject?",
	'subject_deleted' => "Report subject has been successfully deleted.",
	'subject_edit' => "Edit subject",
	'subject_new' => "New subject",
	'subject_saved' => "Report subject has been successfully saved."
);