<?php
// Do not edit this file
$language = array(
	'picture_change' => "Change picture",
	'picture_current' => "Current picture",
	'picture_delete' => "Delete picture",
	'picture_delete?' => "Are you sure you want to delete your profile picture?",
	'picture_deleted' => "Profile picture has been successfully deleted.",
	'picture_edit' => "Edit picture",
	'picture_uploaded' => "Profile picture has been successfully updated."
);