<?php
// Do not edit this file
$language = array(
	'credits' => "Credits",
	'credits_info' => "%s credits",
	'no_package' => "Package does not seem to exist.",
	'no_packages_user' => "Administrator did not create any credit packages yet."
);