<?php
// Do not edit this file
$language = array(
	'ad_approved' => "Classified listing has been successfully approved.",
	'ad_declined' => "Classified listing has been successfully declined.",
	'picture_approved' => "Picture has been successfully approved.",
	'picture_declined' => "Picture has been successfully declined.",
	'picture_fields' => "Picture fields"
);