<?php
// Do not edit this file
$language = array(
	'captcha_default' => "You may not uninstall default form protection library. Set a different default form protection library first before uninstalling this one.",
	'captcha_installed' => "Form protection library has been successfully installed.",
	'captcha_uninstall?' => "Are you sure you want to uninstall this library?",
	'captcha_uninstalled' => "Form protection library has been successfully uninstalled.",
	'no_captcha' => "Form protection library was not found.",
	'no_captchas' => "Form protection libraries were not found."
);