<?php
// Do not edit this file
$language = array(
	'banner_clicks' => "Clicks",
	'banner_code' => "HTML code",
	'banner_count_clicks' => "Count clicks",
	'banner_count_views' => "Count views",
	'banner_delete?' => "Are you sure you want to delete this banner?",
	'banner_deleted' => "Banner has been successfully deleted.",
	'banner_edit' => "Edit banner",
	'banner_keyword_duplicate' => "This keyword is already used in another banner.",
	'banner_new' => "New banner",
	'banner_saved' => "Banner has been successfully saved.",
	'banner_show_secure' => "Display in secure mode",
	'banner_views' => "Views",
	'banners' => "Banners",
	'group_delete?' => "Are you sure you want to delete this banner group?",
	'group_deleted' => "Banner group has been successfully deleted.",
	'group_edit' => "Edit group",
	'group_keyword_duplicate' => "This keyword is already used in another banner group.",
	'group_new' => "New group",
	'group_saved' => "Banner group has been successfully saved.",
	'no_banner' => "Banner does not seem to exist.",
	'no_banners' => "There are no banners in this group yet.",
	'no_group' => "Banner group does not seem to exist.",
	'no_groups' => "There are no banner groups created yet."
);