<?php
// Do not edit this file
$language = array(
	'logged_in_user' => "Logged in as %name",
	'no_users' => "There are no users at this time.",
	'status_unverify' => "Unverify",
	'status_verify' => "Verify",
	'user_approved' => "User has been successfully approved.",
	'user_declined' => "User has been successfully declined.",
	'user_delete?' => "Are you sure you want to delete this user?",
	'user_deleted' => "User has been successfully deleted.",
	'user_edit' => "Edit user",
	'user_new' => "New user",
	'user_saved' => "User has been successfully saved.",
	'user_unverified' => "User's email has been successfully unverified.",
	'user_verified' => "User's email has been successfully verified."
);