<?php
// Do not edit this file
$language = array(
	'no_page' => "Custom page does not seem to exist.",
	'no_pages' => "There are no sub-pages in this section yet.",
	'no_parent' => "Parent page does not seem to exist.",
	'page_custom_file' => "Custom template file",
	'page_custom_file_missing' => "Custom template file does not seem to exist in either of these locations:%1%2",
	'page_delete?' => "Are you sure you want to delete this custom page?",
	'page_deleted' => "Custom page has been successfully deleted.",
	'page_edit' => "Edit page",
	'page_inner' => "Sub-pages",
	'page_keyword_alpha' => "Keyword must contaly only alpha numeric characters, dashes and underscores.",
	'page_keyword_duplicate' => "This keyword is already used in another custom page.",
	'page_keyword_numeric' => "Keyword cannot contain only numbers.",
	'page_keyword_reserved' => "Keyword you chose is not allowed, please choose another one.",
	'page_new' => "New page",
	'page_saved' => "Custom page has been successfully saved.",
	'page_system_delete' => "You may not delete this page because it's used by the system.",
	'page_system_rename' => "You may not change the keyword of this page because it's used by the system.",
	'page_trail' => "Enable trail",
	'page_view' => "View page",
	'pages' => "Pages"
);