<?php
// Do not edit this file
$language = array(
	'friend_active' => "You are already friends with this user.",
	'friend_canceled' => "Friend request has been successfully canceled.",
	'friend_confirmed' => "Friend request has been successfully confirmed.",
	'friend_deleted' => "User has been successfully deleted from your friends list.",
	'friend_duplicate' => "Friend request has already been sent to this user.",
	'friend_duplicate_self' => "Friend request has already been sent to you by this user.",
	'friend_requested' => "Friend request has been sent.",
	'friends_requests' => "Friend requests",
	'no_friend' => "You are not listed as friends with this user.",
	'no_friend_request' => "Friend request does not exist.",
	'no_friend_requests' => "You don't have any friend requests at this time.",
	'no_friends' => "There are no friends at this time.",
	'no_friends_user' => "You don't have anybody in your friends list yet."
);