<?php
// Do not edit this file
$language = array(
	'album_fields' => "Album fields",
	'picture_approved' => "Picture has been successfully approved.",
	'picture_declined' => "Picture has been successfully declined."
);